services:
  mongodb:
    # image: docker.1ms.run/library/mongo:6.0
    image: mongo:6.0
    container_name: hilton_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    # image: docker.1ms.run/library/node:20-slim
    image: node:20-slim
    container_name: hilton_backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - node_cache_backend:/app/node_modules
    environment:
      NODE_ENV: development
      PORT: "5000"
      MONGODB_URI: mongodb://mongodb:27017
      MONGODB_DB: hilton-reservations
      ADMIN_EMAIL: admin@hilton.com
      ADMIN_PASSWORD: admin123
      JWT_SECRET: change-me-in-prod
      JWT_EXPIRE: 7d
      LOG_LEVEL: info
    command: bash -c "npm ci || npm install && sleep 15 && node src/server.js"
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    # image: docker.1ms.run/library/node:20-slim
    image: node:20-slim
    container_name: hilton_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_cache_frontend:/app/node_modules
    environment:
      # 使 Vite 在容器中可从宿主访问
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm ci || npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
  node_cache_backend:
  node_cache_frontend:
